import { Album } from './entities/album.entity';

export const ALBUMS: readonly Album[] = [
  {
    id: 'cody-aventuras',
    name: 'Cody Aventuras',
    description: 'Cody explora selvas, montañas y ruinas perdidas.',
    coverEmoji: '🗺️',
    stickers: [
      {
        id: 'cody-aventuras-01',
        number: 1,
        name: 'Cody explorador',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-aventuras-02',
        number: 2,
        name: 'Cody en la selva',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-aventuras-03',
        number: 3,
        name: 'Cody y la brújula',
        rarity: 'common',
        status: 'missing',
      },
      {
        id: 'cody-aventuras-04',
        number: 4,
        name: 'Cody en la cima',
        rarity: 'rare',
        status: 'owned',
      },
      {
        id: 'cody-aventuras-05',
        number: 5,
        name: 'Cody y el mapa del tesoro',
        rarity: 'rare',
        status: 'duplicate',
      },
      {
        id: 'cody-aventuras-06',
        number: 6,
        name: 'Cody en las ruinas',
        rarity: 'rare',
        status: 'missing',
      },
      {
        id: 'cody-aventuras-07',
        number: 7,
        name: 'Cody cruzando el puente',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-aventuras-08',
        number: 8,
        name: 'Cody y el templo dorado',
        rarity: 'legendary',
        status: 'missing',
      },
      {
        id: 'cody-aventuras-09',
        number: 9,
        name: 'Cody acampando',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-aventuras-10',
        number: 10,
        name: 'Cody héroe de la expedición',
        rarity: 'legendary',
        status: 'owned',
      },
    ],
  },
  {
    id: 'cody-espacio',
    name: 'Cody en el Espacio',
    description: 'Cody viaja entre planetas, cohetes y estrellas.',
    coverEmoji: '🚀',
    stickers: [
      {
        id: 'cody-espacio-01',
        number: 1,
        name: 'Cody astronauta',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-espacio-02',
        number: 2,
        name: 'Cody en el cohete',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-espacio-03',
        number: 3,
        name: 'Cody flotando',
        rarity: 'common',
        status: 'missing',
      },
      {
        id: 'cody-espacio-04',
        number: 4,
        name: 'Cody en la Luna',
        rarity: 'rare',
        status: 'owned',
      },
      {
        id: 'cody-espacio-05',
        number: 5,
        name: 'Cody y Saturno',
        rarity: 'rare',
        status: 'missing',
      },
      {
        id: 'cody-espacio-06',
        number: 6,
        name: 'Cody y el cometa',
        rarity: 'rare',
        status: 'duplicate',
      },
      {
        id: 'cody-espacio-07',
        number: 7,
        name: 'Cody explorando Marte',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-espacio-08',
        number: 8,
        name: 'Cody y el agujero negro',
        rarity: 'legendary',
        status: 'missing',
      },
      {
        id: 'cody-espacio-09',
        number: 9,
        name: 'Cody comandante de la nave',
        rarity: 'legendary',
        status: 'missing',
      },
    ],
  },
  {
    id: 'cody-oceano',
    name: 'Cody bajo el Océano',
    description:
      'Cody bucea entre arrecifes, criaturas marinas y barcos hundidos.',
    coverEmoji: '🌊',
    stickers: [
      {
        id: 'cody-oceano-01',
        number: 1,
        name: 'Cody buzo',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-oceano-02',
        number: 2,
        name: 'Cody y el arrecife',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-oceano-03',
        number: 3,
        name: 'Cody nadando con delfines',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-oceano-04',
        number: 4,
        name: 'Cody y la tortuga',
        rarity: 'rare',
        status: 'missing',
      },
      {
        id: 'cody-oceano-05',
        number: 5,
        name: 'Cody en el barco hundido',
        rarity: 'rare',
        status: 'owned',
      },
      {
        id: 'cody-oceano-06',
        number: 6,
        name: 'Cody y el pulpo gigante',
        rarity: 'rare',
        status: 'missing',
      },
      {
        id: 'cody-oceano-07',
        number: 7,
        name: 'Cody en la fosa abisal',
        rarity: 'legendary',
        status: 'missing',
      },
      {
        id: 'cody-oceano-08',
        number: 8,
        name: 'Cody rey del océano',
        rarity: 'legendary',
        status: 'duplicate',
      },
    ],
  },
  {
    id: 'cody-ciudad',
    name: 'Cody en la Ciudad',
    description:
      'Cody recorre calles, parques y rascacielos de la gran ciudad.',
    coverEmoji: '🏙️',
    stickers: [
      {
        id: 'cody-ciudad-01',
        number: 1,
        name: 'Cody en bicicleta',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-ciudad-02',
        number: 2,
        name: 'Cody en el parque',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-ciudad-03',
        number: 3,
        name: 'Cody en el metro',
        rarity: 'common',
        status: 'missing',
      },
      {
        id: 'cody-ciudad-04',
        number: 4,
        name: 'Cody en el rascacielos',
        rarity: 'rare',
        status: 'missing',
      },
      {
        id: 'cody-ciudad-05',
        number: 5,
        name: 'Cody en el mercado',
        rarity: 'common',
        status: 'owned',
      },
      {
        id: 'cody-ciudad-06',
        number: 6,
        name: 'Cody y los fuegos artificiales',
        rarity: 'rare',
        status: 'duplicate',
      },
      {
        id: 'cody-ciudad-07',
        number: 7,
        name: 'Cody alcalde por un día',
        rarity: 'legendary',
        status: 'missing',
      },
      {
        id: 'cody-ciudad-08',
        number: 8,
        name: 'Cody en el mirador',
        rarity: 'rare',
        status: 'owned',
      },
    ],
  },
];
